### ISSUE TITLE
bio.rules.config是怎么写出来的？

### ISSUE THREAD

**Issue by deepkun** [jeffchy/RE2NN-SEQ#1]
请问，以SNIPS-BIO数据集为例，对应的正则表达式是怎么写出来的呢？是与train.txt对应的吗？换句话说，train.txt里面所有的tag和文本，都能找到对应的正则表达式嘛？

**Comment by jeffchy** [comment]
你好，
”对应的正则表达式是怎么写出来的“：了解一下数据文本之后根据我们对数据和任务的了解写的，例如我们知道我们需要哪些slot tag，针对大多数tag我们写一条或者两条认为比较全面、并且正确的正则。
”train.txt里面所有的tag和文本，都能找到对应的正则表达式嘛？“ 大多数tag 都能找到一条，不一定所有的都可以。对于文本，我们是针对tag、领域知识和对数据的理解写的，不是基于每一条文本。

**Comment by deepkun** [comment]
请问像这种类型的正则，就相当于为condition_temperature写了一条吗？如果我要提取的tag，是无法完全列举出来的，应该怎么表示呢？
@condition_temperature@=(colder | chilly | warm | hot | freezing | hotter | cold | warmer )
$<:>OO * @condition_temperature<:>condition_temperature@ $<:>OO *

**Comment by jeffchy** [comment]
这个case的正则比较简单，是一些列举，但是更加复杂的正则也可以写，但是理论上任何正则表达式都可以。
”如果我要提取的tag，是无法完全列举出来的“ 可以具体一些嘛，什么叫做无法完全列举，是因为太多了还是比较复杂。

**Comment by deepkun** [comment]
> 

背景是这样的，我用很多正则表达式，写了一套比较复杂的规则，从自然语言中，抽取我所关注的一些参数，我认为这些参数，可以归类成你这里的tag
“无法完全列举”是指要提取某一个tag，对应的具体的参数太多了，比如 我看你这里有一个tag：artist，我不能把所有artist都列举出来
我有一个正则的例子是：
PARAM_REPR = '[a-zA-Z0-9_\.: \-%/"“”=&()个]'
pattern = f'(({PARAM_REPR}+)(<=|>=|\<|\=|\>)({PARAM_REPR}+))'
这个正则，能匹配的三个部分，分别对应的tag 是 param，relation，value
所以仿照你bio.config.rules，我写了一个这种表达：
(@sw_param<:>param@) (@equal<:>relation@) (@sw_value<:>value@)
我看你的bio.config.rules里面，把sw_param, equal, sw_value都列举出来了，但我这里，是没法列举的，有两个问题：
1. 这种转换方式是否正确？
2. 类似这种不能列举的情况，应该怎么处理呢？
谢谢~~

**Comment by jeffchy** [comment]
@variable<:>tag@是我定义的一个语法，方便我把定义的variable（通常是列举）替换进去变成正则表达式。
定义变量不是必须的。如果你不考虑B-I-O，可能可以写成
@relation@=(<=|>=|<|=|>)
$<:>param + @relation<:>rel@ $<:>value +
其中$的意思是任意词
如果你想限定的话可以定义成类似：
@PARAM_REPR@=(A|B|C....|个)
@PARAM_REPR<:>param@ + @relation<:>rel@ @PARAM_REPR<:>value@ +

**Comment by jeffchy** [comment]
另外 我这边是word-level的，如果你是char level的话，需要对分词进行修改。

**Comment by deepkun** [comment]
> 另外 我这边是word-level的，如果你是char level的话，需要对分词进行修改。

好的，谢谢，我理解一下，再修改

**Comment by deepkun** [comment]
> 另外 我这边是word-level的，如果你是char level的话，需要对分词进行修改。

大佬，打扰了，之前只用一条正则做demo，跟大佬讨论之后，加了几条，准确率下降到原来的5分之一了，请问这个调参有什么trick吗？

**Comment by jeffchy** [comment]
你好，你要确定每个正则的正确性，有的正则如果写错了会影响本来对了的正则，你可以分别去看每一条正则有没有打扰你想要的效果～-------- 原始邮件 --------发件人： deepkun ***@***.***>日期： 2022年1月22日周六 傍晚5:52收件人： jeffchy/RE2NN-SEQ ***@***.***>抄送： Jeff Chiang ***@***.***>, State change ***@***.***>主    题： Re: [jeffchy/RE2NN-SEQ] bio.rules.config是怎么写出来的？ (Issue #1)



另外 我这边是word-level的，如果你是char level的话，需要对分词进行修改。



大佬，打扰了，之前只用一条正则做demo，跟大佬讨论之后，加了几条，准确率下降到原来的5分之一了，请问这个调参有什么trick吗？
