### ISSUE TITLE
run the code

### ISSUE THREAD

**Issue by Absurd233** [jeffchy/RE2NN-SEQ#2]
请问一下python main.py --arg_path ../model_seq/config_file_path.res代码运行时出行错误：
G:\Anaconda3\envs\emnlp21\python.exe: can't open file 'main.py': [Errno 2] No such file or directory
怎么处理啊？

**Comment by jeffchy** [comment]
“python.exe: can't open file 'main.py':” it seems like you don't run code in the folder with 'main.py'?

**Comment by Absurd233** [comment]
谢谢您的回复，解决了can't open file 'main.py'的问题。
现在已经切换到src_seq目录下了，出现了‘main.py: error: unrecognized arguments: --arg_path ../model_seq/config_file_path.res’这样一个错误，请问一下应该怎么运行代码，可以给个样例吗？麻烦了。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jeffchy/RE2NN-SEQ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jeffchy/RE2NN-SEQ] run the code (Issue #2)





 
“python.exe: can't open file 'main.py':” it seems like you don't run code in the folder with 'main.py'?

**Comment by jeffchy** [comment]
It should be --args_path, sorry about my typo.
config_file_path.res should be replaced by a specific model config file

**Comment by Absurd233** [comment]
感谢回复，我按照您的方法试了，但报了这样的错误
![image](https://user-images.githubusercontent.com/60883571/162687903-2248ffae-7b11-4d1e-8307-53e1491b2604.png)

**Comment by jeffchy** [comment]
might be caused by the different version of pytorch.
to fix that, you can 
1. switch the pytorch version to 1.3.1
or 2. cast the tensor inp to long tensors, (inp.long())

**Comment by Absurd233** [comment]
感谢已经解决了这个问题，但现在又出了一个新的问题：好像缺失了文件：
`FileNotFoundError: [Errno 2] No such file or directory: '../data/ATIS-ZH-BIO/automata/IIID.automata.0309063657-1615271817.9054942.svd.2best.104states.random.3splits.250-0.0023.bio.rules.v1.config.pkl'`
![image](https://user-images.githubusercontent.com/60883571/162691555-f00c2a04-fba7-4cfb-89ff-fb8583ae530f.png)

**Comment by Absurd233** [comment]
谢谢大佬，问题已经解决，麻烦了。
