### ISSUE TITLE
Run and train the decomposed transducer

### ISSUE THREAD

**Issue by superlrt** [jeffchy/RE2NN-SEQ#4]
你好，我在运行最后一条指令时，报了如下错误：File "../src_seq/farnn/model_decompose_single.py", line 76, in init_forward_parameters
    self.embed_r_generalized = nn.Parameter(torch.matmul(_pinv, _V), requires_grad=True) # D x R
RuntimeError: size mismatch, m1: [100 x 8], m2: [47 x 150] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:197

指令中--automata_path 用的是运行“python create_dataset_automata.py --independent 2 --decompose 1 --rule_name bio.rules.config --dataset SNIPS-BIO --k_best 3 --automata_name my_rule_decomposed”指令后生成的IIID.automata.....pkl文件路径。数据换成了其他数据集。请问是什么原因造成的错误？
@jeffchy

**Comment by jeffchy** [comment]
你使用的是针对SNIPS撰写的正则表达式，分解后的自动机对应的三个矩阵维度分别为 VxR, SxR, SxR 其中V是SNIPS数据集的词表大小，且要等于self.embedding.weight.data # V x D 中的这个V，并且要是对应的。你如果换了数据集，词表大小看起来就变了，就对不上了。

```
      self.S1 = nn.Parameter(self.pad_additional_states(torch.from_numpy(S1).float()), requires_grad=True) # S x R
      self.S2 = nn.Parameter(self.pad_additional_states(torch.from_numpy(S2).float()), requires_grad=True) # S x R
      self.V_embed = nn.Parameter(torch.from_numpy(V).float(), requires_grad=bool(self.args.train_V_embed)) # V x R
      embed_init_weight = self.embedding.weight.data # V x D
      _pinv = embed_init_weight.pinverse() # D x V
      _V = self.V_embed.data # V x R
      self.embed_r_generalized = nn.Parameter(torch.matmul(_pinv, _V), requires_grad=True) # D x R
```

**Comment by superlrt** [comment]
谢谢，我懂啦! 还有一个问题：
指令“python main.py --independent 2 --dataset SNIPS-BIO --method decompose --automata_path your_decomposed_automata.pkl --train_portion 1 --beta 0.1--update_nonlinear tanh --lr 0.001”中，--automata_path 的路径和RE.py中def assign_automata(args_bak)函数的args_bak.automata_path路径是否一致？
@jeffchy

**Comment by jeffchy** [comment]
并不需要一致，RE.py中的assign automata的作用是用已经固定下来的几个数据的规则的自动机，跑正则表达式效果的。主要是验证正则表达式效果以及跑baseline会用到一些score之类的东西。
如果你换了数据，你应该尝试写自己的规则、转化自己的自动机。

**Comment by superlrt** [comment]
谢谢，但我还是没有完全理解。如果我使用自己的数据，需要转化两个自动机，分别用于RE.py中的assign automata和main.py所用的分解过的自动机，对吗？ @jeffchy

**Comment by jeffchy** [comment]
你好，是的。
因为SlotBatchDataset中使用了RE.py，先用assign automata跑了一下未分解的正则表达式的自动机，得到正则表达式结果主要用于跑baseline。所以如你所说，在两个地方加上就行了（建议新命名一个dataset，然后参数传入对应的分解后的自动机参数路径，然后再assign_automata里面也加入确定的自动机文件路径）。

**Comment by superlrt** [comment]
> 

请问，我换了数据集，并且重写了相应的正则表达式。为什么还是报错如下呀？self.embed_r_generalized = nn.Parameter(torch.matmul(_pinv, _V), requires_grad=True) # D x R
RuntimeError: size mismatch, m1: [100 x 8], m2: [47 x 150] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:197
@jeffchy

**Comment by jeffchy** [comment]
你好 你用的是 train_decompose 吗
这个报错的原因是 pretrained embedding 的初始化错误 8x100 看起来是不对的，pinv的维度应该是DxV (static embedding 维度 x 你的新数据集的词表大小)。

由于你添加了新的数据集，所以需要生成新的pretrained embedding （glove、fasttext、或者static后的bert），生成pretrained embedding的代码见函数见 src_seq.data.make_glove/fasttext_embedding。
_pinv 是pretrained embedding 的 pseudo-inverse （embedding部分具体见论文3.4的最后部分）

**Comment by jeffchy** [comment]
create embedding 的部分已经包括在 
create_slot_dataset(dataset_name) 里面，确保这一步是正确的（生成了正确的vocab file，以及对应的embedding）

**Comment by superlrt** [comment]
你好，请问怎样可以看到模型测试后得到的结果呀？
@jeffchy

**Comment by jeffchy** [comment]
the all_pred_label in the train_decompose.py and val.py are what you want, I think you can also call val_xxx_verbose() in val.py
https://github.com/jeffchy/RE2NN-SEQ/blob/e50ce2aa5ffafcbdfd74b06ec5a956305f05d2a4/src_seq/train_decompose.py#L196

**Comment by superlrt** [comment]
请问，如何才能看到模型对测试集标注后的具体文字结果呀
@jeffchy

**Comment by jeffchy** [comment]
i2s means id-to-slot-label
https://github.com/jeffchy/RE2NN-SEQ/blob/e50ce2aa5ffafcbdfd74b06ec5a956305f05d2a4/src_seq/train_decompose.py#L31
use it to convert the predicted slot label id to slot label.

**Comment by superlrt** [comment]
请问，我使用了自己的规则和数据。在运行python main.py --dataset HD-ZH-BIO --method onehot --automata_path ../data/HD-ZH-BIO/automata/my_rule10.122.ID2  --normalize_automata none --rand_constant 0
这条指令时，报错如下：
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    train_slot_onehot(args)
  File "../src_seq/train_onehot.py", line 142, in train_slot_onehot
    results_train = val_onehot(slot_dataloader_train, model, args, s2i['o'], i2s, i2t)
  File "../src_seq/val.py", line 19, in val_onehot
    for batch in data:
  File "/home/lrt21/miniconda3/envs/lrt_py3/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/lrt21/miniconda3/envs/lrt_py3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lrt21/miniconda3/envs/lrt_py3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lrt21/miniconda3/envs/lrt_py3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "../src_seq/data.py", line 208, in __getitem__
    're': np.array(self.re[idx], dtype=np.float32),
IndexError: list index out of range
这是由于什么原因造成的呢？
@jeffchy

**Comment by jeffchy** [comment]
看看batch的内容？仅有这些我不太能确定

**Comment by superlrt** [comment]
问题找到原因了，是因为没有换代码里的automata路径，导致读错了自动机文件。谢谢！

**Comment by superlrt** [comment]
请问，从word_level改为char_level,需要在哪里修改呢、
@jeffchy

**Comment by jeffchy** [comment]
理论上可行，目前代码暂时不支持。
需要修改一系列东西，比如 rule_utils 里面的 tokenizer
而且变成char level之后没有办法和 pretrained word embedding进行对齐，相应比较难用上pretrained的模型/embedding，不过也许可以加入feature

**Comment by superlrt** [comment]
好的谢谢。请问，理论上分解后的automata测试效果应该优于未分解的automata，是这样吗？
@jeffchy

**Comment by jeffchy** [comment]
理论上应该差不多。你可以把未分界的automata （onehot）看成原来的规则，分解后如果近似完美的话应该效果保持一致，如果近似的很差可能效果会下降。但是由于分解后可以融入word embedding，有的时候反而效果会好一点点。分解是为了更好的变成神经网络进行训练。

**Comment by superlrt** [comment]
未分解的automata也是变成神经网络，再进行训练，但分解的目的是让automata与神经网络更相似，对吗
@jeffchy

**Comment by jeffchy** [comment]
可以这么理解
